@URL = {{host}}/protobuf

##################################

POST {{URL}}
Content-Type: application/json

{
  "file": "rank.proto",
  "packageName": "wesing.service.rank_center",
  "serviceName": "RankCenter",
  "action": "GetActivityConfig",
  "address": "9.131.137.13:9000",
  "payload": {
    "activity_id": "5f4770ea45d664a6f853e462"
  }
}