/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ProtobufSchema {
  file: string
  address: string
  packageName: string
  serviceName: string
  action: string
  payload?: {
    [k: string]: unknown
  }
}
